version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3309:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  mongo:
    image: mongo
    restart: always
    ports:
      - 27023:27017
    volumes:
       - mongo_data:/data/db
       
volumes:
  mongo_data:



#version: '3'

#services:
###> doctrine/doctrine-bundle ###
  #database:
   # image: postgres:${POSTGRES_VERSION:-16}-alpine
   # environment:
    #  POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
     # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      #POSTGRES_USER: ${POSTGRES_USER:-app}
    #volumes:
     # - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

#volumes:
###> doctrine/doctrine-bundle ###
  #database_data:
###< doctrine/doctrine-bundle ###
