class Livraison {
	id
	date_livraison
	observation
	**ligneLivraisons**
	**Commande**
}

class Client {
	id
	reference_client
	type
	coefficient
	reduction
	**Employe**
	**utilisateur**
	**commandes**
}

class Fournisseur {
	id
	numero_siret
	nom_entreprise
	categorie_fournisseur
	adresse
	email
	telephone
	**Produit**
}

class LigneLivraison {
	id
	quantite_livree
	**Livraison**
	**Produit**
	libelle
	prix_vente
}

class Employe {
	id
	poste
	**clients**
	**Utilisateur**
}

class Utilisateur {
	id
	email
	roles
	password
	nom
	prenom
	**client**
	**employe**
	dateNaissance
	telephone
	isVerified
	sexe
	adresse
	CP
	ville
}

class ResetPasswordRequest {
	id
	**user**
	selector
	hashedToken
	requestedAt
	expiresAt
}

class Contact {
	id
	nom
	prenom
	sujet
	telephone
	email
	message
}

class Produit {
	id
	reference
	libelle
	dimenssion
	couleur
	description
	prix_achat
	photo
	actif
	quantite_stock
	stock_alert
	**fournisseur**
	**Categorie**
	**ligneCommandes**
	**ligneLivraisons**
	remise
}

class LigneCommande {
	id
	quantite
	libelle
	prix_vente
	**Commande**
	**Produit**
	photo
}

class Commande {
	id
	numero_facture
	date_facture
	date_commande
	total_commande
	adresse_livraison
	cp_livraison
	ville_livraison
	adresse_facturation
	cp_facturation
	ville_facturation
	statut
	payee
	mode_paiement
	total_paye
	**ligneCommandes**
	**livraisons**
	**Client**
	image
}

class Categorie {
	id
	nom_categorie
	photo
	**produits**
	**parent**
	**categories**
}

Livraison "1"--"*" LigneLivraison
Client "1"--"*" Commande
Fournisseur "1"--"*" Produit
Employe "1"--"*" Client
Produit "1"--"*" LigneCommande
Produit "1"--"*" LigneLivraison
Commande "1"--"*" LigneCommande
Commande "1"--"*" Livraison
Categorie "1"--"*" Produit
Categorie "1"--"*" Categorie


hide methods
hide circle

